name = "Vanilla"
license = "MIT"
licenselink = ""
description = "A super concise theme for Hugo"
homepage = "https://github.com/oeyoews/hugo-theme-even"
tags = ["responsive", "blog", "simple", "clean", "highlight.js", "syntax highlighting"]
features = ["responsive", "blog", "simple", "clean", "highlight.js", "syntax highlighting"]
min_version = "0.60.0"

[author]
  name = "oeyoews"
  homepage = "https://github.com/oeyoews"

# If porting an existing theme
[original]
  name = "hexo-theme-even"
  homepage = ""
  repo = "https://github.com/oeyoews/hexo-theme-even"
